[{$smarty.block.parent}]
[{if $oViewConf->isAmazonActive() && !$oViewConf->isAmazonExclude() && $oViewConf->displayExpressInMiniCartAndModal()}]
    [{if $oViewConf->isFlowCompatibleTheme()}]
        [{if !$oViewConf->isAmazonSessionActive()}]
            [{include file="@osc_amazonpay/frontend/dd_layout_page_header_icon_menu_minibasket_functions_flow.tpl"}]
        [{else}]
            <div class="clearfix" style="margin-bottom: 15px;"></div>
            [{include file='@osc_amazonpay/frontend/amazonpayhint.tpl' withBreak=true}]
        [{/if}]
    [{else}]
        [{if !$oViewConf->isAmazonSessionActive()}]
            [{include file="@osc_amazonpay/frontend/dd_layout_page_header_icon_menu_minibasket_functions_wave.tpl"}]
        [{else}]
            <div class="clearfix" style="margin-bottom: 15px;"></div>
            [{include file='@osc_amazonpay/frontend/amazonpayhint.tpl' withBreak=true alignRight=true}]
        [{/if}]
    [{/if}]
[{/if}]