[{if $oViewConf->isAmazonActive() && $oViewConf->isAmazonSessionActive()}]
    [{if $oViewConf->isAmazonPaymentPossible()}]
        [{if $oViewConf->isFlowCompatibleTheme()}]
            [{include file="@osc_amazonpay/frontend/shippingandpayment_flow.tpl"}]
        [{else}]
            [{include file="@osc_amazonpay/frontend/shippingandpayment_wave.tpl"}]
        [{/if}]
    [{else}]
        [{if $oViewConf->isFlowCompatibleTheme()}]
            [{include file="@osc_amazonpay/frontend/shippingandpayment_error_flow.tpl"}]
        [{else}]
            [{include file="@osc_amazonpay/frontend/shippingandpayment_error_wave.tpl"}]
        [{/if}]
    [{/if}]
[{else}]
    [{$smarty.block.parent}]
[{/if}]