[{$smarty.block.parent}]
[{if $oViewConf->isAmazonActive() && !$oViewConf->isAmazonExclude() && $oViewConf->displayExpressInMiniCartAndModal()}]
    [{if $oViewConf->isFlowCompatibleTheme()}]
        [{if !$oViewConf->isAmazonSessionActive()}]
            [{include file="amazonpay/dd_layout_page_header_icon_menu_minibasket_functions_flow.tpl"}]
        [{else}]
            <div class="clearfix" style="margin-bottom: 15px;"></div>
            [[{include file='amazonpay/amazonpayhint.tpl'}]
        [{/if}]
    [{else}]
        [{if !$oViewConf->isAmazonSessionActive()}]
            [{include file="amazonpay/dd_layout_page_header_icon_menu_minibasket_functions_wave.tpl"}]
        [{else}]
            <div class="clearfix" style="margin-bottom: 15px;"></div>
            [{include file='amazonpay/amazonpayhint.tpl' withBreak=true }]
        [{/if}]
    [{/if}]
[{/if}]