[{if $oViewConf->isAmazonSessionActive() && !$oViewConf->isAmazonExclude()}]
    [{assign var="billing" value=$oView->getAmazonBillingAddress()}]
    <div class="col-lg-9 offset-lg-3" id="addressText">
        [{if $billing.oxcompany}] [{$billing.oxcompany}]<br> [{/if}]
        [{if $billing.oxaddinfo}] [{$billing.oxaddinfo}]<br>[{/if}]
        [{if $billing.oxustid}] [{oxmultilang ident="VAT_ID_NUMBER"}] [{$billing.oxustid}]<br> [{/if}]
        [{if $billing.oxsal || $billing.oxfname || $billing.oxlname}][{$billing.oxsal|oxmultilangsal}]&nbsp;[{$billing.oxfname}]&nbsp;[{$billing.oxlname}]<br>[{/if}]
        [{if $billing.oxstreet || $billing.oxstreetnr}][{$billing.oxstreet}]&nbsp;[{$billing.oxstreetnr}]<br>[{/if}]
        [{if $billing.oxstateid}][{$billing.oxstateid}] [{/if}]
        [{if $billing.oxzip || $billing.oxcity}][{$billing.oxzip}]&nbsp;[{$billing.oxcity}]<br>[{/if}]
        [{if $billing.oxcountry}][{$billing.oxcountry}]<br><br>[{/if}]
        [{if $billing.oxusername}]<strong>[{oxmultilang ident="EMAIL"}]</strong> [{$billing.oxusername}]<br><br>[{/if}]
        [{if $billing.oxfon}]<strong>[{oxmultilang ident="PHONE"}]</strong> [{$billing.oxfon}]<br>[{/if}]
        [{if $billing.oxfax}]<strong>[{oxmultilang ident="FAX"}]</strong> [{$billing.oxfax}]<br>[{/if}]
        [{if $billing.oxmobfon}]<strong>[{oxmultilang ident="CELLUAR_PHONE"}]</strong> [{$billing.oxmobfon}]<br>[{/if}]
        [{if $billing.oxprivfon}]<strong>[{oxmultilang ident="PERSONAL_PHONE"}]</strong> [{$billing.oxprivfon}]<br>[{/if}]
    </div>
[{else}]
    [{$smarty.block.parent}]
[{/if}]