[{$smarty.block.parent}]
[{if $blCanBuy && $oViewConf->isAmazonActive() && $oViewConf->displayExpressInPDP() && !$oViewConf->isAmazonExclude($oDetailsProduct->oxarticles__oxid->value)}]
    [{if !$oViewConf->isAmazonSessionActive()}]
        [{include file='@osc_amazonpay/frontend/details_productmain_tobasket.tpl'}]
    [{else}]
        [{include file='@osc_amazonpay/frontend/amazonpayhint.tpl' withBreak=true}]
    [{/if}]
[{/if}]
