[{assign var="oBillingAddress" value=$oView->getFilteredBillingAddress()}]
[{if $oViewConf->isAmazonSessionActive() && !$oViewConf->isAmazonExclude() && $oBillingAddress}]
    [{include file="amazonpay/flow_filtered_billing_address.tpl" billadr=$oBillingAddress}]
[{else}]
    [{$smarty.block.parent}]
[{/if}]