[{if $oViewConf->isAmazonActive() && $oViewConf->isAmazonSessionActive() && !$oViewConf->isAmazonExclude()}]
    [{include file="amazonpay/flow_checkout_order_address.tpl"}]
[{else}]
    [{$smarty.block.parent}]
[{/if}]