[{if $oViewConf->isAmazonActive() && $oViewConf->isAmazonSessionActive() && !$oViewConf->isAmazonPaymentPossible()}]
    [{include file="amazonpay/flow_shippingandpayment.tpl"}]
[{else}]
    [{$smarty.block.parent}]
[{/if}]