[{if ($oViewConf->isAmazonActive() && $oViewConf->isAmazonPaymentPossible()) || !$oViewConf->isAmazonActive()}]
    [{$smarty.block.parent}]
[{else}]
    [{include file="amazonpay/wave_shippingandpayment.tpl"}]
[{/if}]