[{if $oViewConf->isFlowCompatibleTheme()}]
    [{$smarty.block.parent}]
    [{if $oViewConf->isAmazonActive() && !$oViewConf->isAmazonExclude() && !$oViewConf->isAmazonSessionActive() && $oViewConf->displayInMiniCartAndModal()}]
        [{include file="amazonpay/basket_btn_next_bottom_flow.tpl"}]
    [{/if}]
[{else}]
    [{if $oViewConf->isAmazonActive() && !$oViewConf->isAmazonExclude() && !$oViewConf->isAmazonSessionActive() && $oViewConf->displayInMiniCartAndModal()}]
        [{include file="amazonpay/wave_basket_btn_next_bottom_wave.tpl"}]
    [{/if}]
    [{$smarty.block.parent}]
[{/if}]