[{if $oViewConf->getAmazonPaymentId()|array_key_exists:$oView->getPaymentList() && !$oViewConf->isAmazonExclude()}]
    [{if $oViewConf->isFlowCompatibleTheme()}]
        [{include file='amazonpay/change_payment_block_flow.tpl'}]
    [{else}]
        [{include file='amazonpay/change_payment_block_wave.tpl'}]
    [{/if}]
[{/if}]
[{if !$oViewConf->isAmazonSessionActive() || $oViewConf->isAmazonExclude()}]
    [{$smarty.block.parent}]
[{elseif $oViewConf->getAmazonPaymentId()|array_key_exists:$oView->getPaymentList()}]
    [{if $oViewConf->isFlowCompatibleTheme()}]
        [{include file='amazonpay/change_payment_form_flow.tpl'}]
    [{else}]
        [{include file='amazonpay/change_payment_form_wave.tpl'}]
    [{/if}]
[{/if}]
