[{if $sPaymentID === $oViewConf->getAmazonExpressPaymentId()}]
    [{include file='amazonpay/payment_amazonpay.tpl' buttonId="AmazonPayButtonChangePayment" buttonClass="small"}]
[{else}]
    [{$smarty.block.parent}]
[{/if}]