[{if $oViewConf->isAmazonActive() && $oViewConf->isAmazonSessionActive()}]
    [{if $oViewConf->isAmazonPaymentPossible()}]
        [{include file="amazonpay/shippingandpayment.tpl"}]
    [{else}]
        [{include file="amazonpay/shippingandpayment_error.tpl"}]
    [{/if}]
[{else}]
    [{$smarty.block.parent}]
[{/if}]