name: Development

on: [ push, pull_request ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  MODULE_PATH: 'osc/amazonpay'

jobs:
  styles:
    strategy:
      matrix:
        php: [ '7.0' ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current module
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          extensions: gd, zip

      - name: Install module dependencies
        run: composer install --no-interaction --no-progress

      - name: Run phpcs
        if: always()
        run: composer phpcs
