name: Development

on: [ push, pull_request ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  MODULE_PATH: 'extensions/amazonpay'

jobs:
  styles:
    strategy:
      matrix:
        php: [ '8.1' ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current module
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          extensions: gd, zip

      - name: Install module dependencies
        run: composer install --no-interaction --no-progress

      - name: Run phpcs
        if: always()
        run: composer phpcs

      - name: Run phpmd
        if: always()
        run: composer phpmd-report || composer phpmd

      - name: Run phpstan
        if: always()
        run: composer phpstan

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: StylesLog-${{ matrix.php }}
          if-no-files-found: ignore
          path: |
            tests/reports/phpmd.report.json
